In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

np.random.seed(1)

In [3]:
# read data
df = pd.read_csv('../data/Strategic_Subject_List_-_Historical.csv')
df.head()

/tmp/ipykernel_2205/2982276228.py:2: DtypeWarning: Columns (47) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/Strategic_Subject_List_-_Historical.csv')

,SSL SCORE,PREDICTOR RAT AGE AT LATEST ARREST,PREDICTOR RAT VICTIM SHOOTING INCIDENTS,PREDICTOR RAT VICTIM BATTERY OR ASSAULT,PREDICTOR RAT ARRESTS VIOLENT OFFENSES,PREDICTOR RAT GANG AFFILIATION,PREDICTOR RAT NARCOTIC ARRESTS,PREDICTOR RAT TREND IN CRIMINAL ACTIVITY,PREDICTOR RAT UUW ARRESTS,SEX CODE CD,...,RAW_HEAT_SCORE,STATUS I,PRE RAW HEAT SCORE,TRAP FLAGS,SSL FLAGS,LATITUDE,LONGITUDE,CENSUS TRACT,COMMUNITY AREA,LOCATION
0,306,20-30,0,0,0,0,0,-0.3,0,M,...,0.09110,Y,9110,NaN,NaN,NaN,NaN,NaN,,NaN
1,352,20-30,0,1,0,0,0,0.0,0,M,...,0.09949,Y,9949,NaN,NaN,NaN,NaN,NaN,,NaN
2,349,20-30,0,0,2,0,2,0.0,0,M,...,0.09908,Y,9908,NaN,NaN,NaN,NaN,NaN,,NaN
3,344,20-30,0,0,3,0,0,-0.3,0,M,...,0.09810,Y,9810,NaN,NaN,NaN,NaN,NaN,,NaN
4,343,20-30,0,0,1,0,0,0.4,0,M,...,0.09794,Y,9794,NaN,NaN,NaN,NaN,NaN,,NaN

In [4]:
df.drop(['MAJORITY DIST', 'DLST', 'IDOC RES CITY', 'IDOC RES STATE CODE', 'IDOC RES ZIP CODE', 'IDOC CPD DIST', 'TRAP FLAGS', 'SSL FLAGS'], axis=1, inplace = True)

In [5]:
# One-hot encode the data using pandas get_dummies
df = pd.get_dummies(df)
df.head()

,SSL SCORE,PREDICTOR RAT VICTIM SHOOTING INCIDENTS,PREDICTOR RAT VICTIM BATTERY OR ASSAULT,PREDICTOR RAT ARRESTS VIOLENT OFFENSES,PREDICTOR RAT GANG AFFILIATION,PREDICTOR RAT NARCOTIC ARRESTS,PREDICTOR RAT TREND IN CRIMINAL ACTIVITY,PREDICTOR RAT UUW ARRESTS,STOP ORDER NO,LATEST DATE,...,"LOCATION_(42.0091482507601, -87.6786204697715)","LOCATION_(42.0094119794164, -87.6639582885693)","LOCATION_(42.0123943960856, -87.9044880070487)","LOCATION_(42.0152551375773, -87.8135847059243)","LOCATION_(42.0156902536203, -87.6995191177754)","LOCATION_(42.0157210660336, -87.6871169320041)","LOCATION_(42.0159407400186, -87.6665351054558)","LOCATION_(42.0160077100778, -87.6801484583196)","LOCATION_(42.0160507111001, -87.6733216373639)","LOCATION_(42.0212563434854, -87.6698316360494)"
0,306,0,0,0,0,0,-0.3,0,NaN,2012,...,0,0,0,0,0,0,0,0,0,0
1,352,0,1,0,0,0,0.0,0,NaN,2015,...,0,0,0,0,0,0,0,0,0,0
2,349,0,0,2,0,2,0.0,0,NaN,2016,...,0,0,0,0,0,0,0,0,0,0
3,344,0,0,3,0,0,-0.3,0,NaN,2014,...,0,0,0,0,0,0,0,0,0,0
4,343,0,0,1,0,0,0.4,0,NaN,2015,...,0,0,0,0,0,0,0,0,0,0